### ISSUE TITLE
Flask 2.2.0 removes MethodViewType

### ISSUE THREAD

**Issue by anmcn** [marshmallow-code/flask-smorest#384]
flask_smorest does not work with flask 2.2.0:
```
  File ".../api/__init__.py", line 8, in <module>
    from flask_smorest import Api, Blueprint, abort
  File ".../venv/lib/python3.9/site-packages/flask_smorest/__init__.py", line 6, in <module>
    from .blueprint import Blueprint  # noqa
  File ".../venv/lib/python3.9/site-packages/flask_smorest/blueprint.py", line 43, in <module>
    from flask.views import MethodViewType
ImportError: cannot import name 'MethodViewType' from 'flask.views' (.../venv/lib/python3.9/site-packages/flask/views.py)
```
This is due to MethodViewType being changed from a metaclass into a `__init_subclass__` method:

https://github.com/pallets/flask/commit/45174bf9a1e96e51ce589c7aa2c151249d1fdf11

**Comment by lafrech** [comment]
There are other issues with Flask 2.2.

- [x] _app_ctx_stack.top is deprecated and warnings break etag tests (#392)
- [x] our generate_etag is also broken, we need to use app.json

Fixes incoming. I think I'll issue version 0.39 dropping flask < 2.2.

**Comment by lafrech** [comment]
Done and released, with support for Flask 2.2+ and <2.2.
