### PR TITLE
Fix: Flask 2.2 'MethodViewType' Removal

### LINKED ISSUE #384: Flask 2.2.0 removes MethodViewType
flask_smorest does not work with flask 2.2.0:
```
  File ".../api/__init__.py", line 8, in <module>
    from flask_smorest import Api, Blueprint, abort
  File ".../venv/lib/python3.9/site-packages/flask_smorest/__init__.py", line 6, in <module>
    from .blueprint import Blueprint  # noqa
  File ".../venv/lib/python3.9/site-packages/flask_smorest/blueprint.py", line 43, in <module>
    from flask.views import MethodViewType
ImportError: cannot import name 'MethodViewType' from 'flask.views' (.../venv/lib/python3.9/site-packages/flask/views.py)
```
This is due to MethodViewType being changed from a metaclass into a `__init_subclass__` method:

https://github.com/pallets/flask/commit/45174bf9a1e96e51ce589c7aa2c151249d1fdf11

### PR DESCRIPTION
**Pull request by 0x78f1935**
Fixes: https://github.com/marshmallow-code/flask-smorest/issues/384

```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/development/development/tests/dist/webserver.py", line 9, in <module>
    from backend import Webserver
  File "/var/lib/jenkins/workspace/development/development/tests/dist/backend/__init__.py", line 15, in <module>
    from backend.extensions import init_app as _init_extensions
  File "/var/lib/jenkins/workspace/development/development/tests/dist/backend/extensions/__init__.py", line 9, in <module>
    from flask_smorest import Api  # noqa: E402
  File "/var/lib/jenkins/workspace/development/.pyenv-python3/lib/python3.9/site-packages/flask_smorest/__init__.py", line 6, in <module>
    from .blueprint import Blueprint  # noqa
  File "/var/lib/jenkins/workspace/development/.pyenv-python3/lib/python3.9/site-packages/flask_smorest/blueprint.py", line 46, in <module>
    from flask.views import MethodViewType
ImportError: cannot import name 'MethodViewType' from 'flask.views'
```

Same issue flask_apispec [has](https://stackoverflow.com/questions/73221330/attributeerror-module-flask-views-has-no-attribute-methodviewtype)
Fix inspired by [this](https://github.com/jmcarp/flask-apispec/pull/238/files) topic.
Might fix https://github.com/marshmallow-code/flask-smorest/pull/386 PR too.

### CODE REVIEW

**Comment by lafrech** [comment]
Thanks. Currently AFK. Will look into this when back from holidays.

**Comment by lafrech** [comment]
For the record, same fix was applied to apiflask.

Thanks.

**Comment by AbdealiLoKo** [comment]
Hi, is there a plan to publish this on pypi ?

**Comment by lafrech** [comment]
See https://github.com/marshmallow-code/flask-smorest/issues/384#issuecomment-1209611787.

I need to fix other Flask 2.2 issues first (work in progress).
